# display parameters
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
BORDER_SIZE = 200

# asteroids parameters
ASTEROID_NUMBER = 5
ASTEROID_MAX_SPEED = 0.3
ASTEROID_MIN_MASS = 100000

ENABLE_ASTEROID_COLLISION = False
USE_IRREGULAR_POLYGONS = False

# ship parameters
SHIP_DRAG_COEFF = 0.95
SHIP_ACCELERATION = 0.0005
SHIP_TURN_RATE = 0.002
SHIP_SIZE = 30
