# display parameters
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
BORDER_SIZE = 200

# asteroidsGroup parameters
ASTEROID_NUMBER = 5
ASTEROID_MAX_SPEED = 0.2
ASTEROID_MIN_MASS = 100000

ENABLE_ASTEROID_COLLISION = False
USE_IRREGULAR_POLYGONS = False

# ship parameters
SHIP_DRAG_COEFF = 0.98
SHIP_ACCELERATION = 0.001
SHIP_TURN_RATE = 0.002
SHIP_SIZE = 30
SHIP_FIRING_RATE = 250  # 500ms delay between shots

SHIP_USE_MOUSE = False
